"""Browser effects — backward-compatibility shim.

All effect classes have been moved to ``demodsl.effects.browser`` (one file
per effect).  This module re-exports every public name so that existing
imports continue to work unchanged.
"""

from demodsl.effects.browser import (  # noqa: F401 — re-exports
    BubblesEffect,
    CalloutArrowEffect,
    ConfettiEffect,
    CountdownTimerEffect,
    CursorTrailCometEffect,
    CursorTrailEffect,
    CursorTrailFireEffect,
    CursorTrailGlowEffect,
    CursorTrailLineEffect,
    CursorTrailParticlesEffect,
    CursorTrailRainbowEffect,
    EmojiRainEffect,
    FireworksEffect,
    FrostedGlassEffect,
    GlowEffect,
    HighlightEffect,
    MagneticHoverEffect,
    MatrixRainEffect,
    MorphingBackgroundEffect,
    NeonGlowEffect,
    PartyPopperEffect,
    ProgressBarEffect,
    RippleEffect,
    ShockwaveEffect,
    SnowEffect,
    SparkleEffect,
    SpotlightEffect,
    StarBurstEffect,
    SuccessCheckmarkEffect,
    TextHighlightEffect,
    TextScrambleEffect,
    TooltipAnnotationEffect,
    TypewriterEffect,
    register_all_browser_effects,
)

__all__ = [
    "BubblesEffect",
    "CalloutArrowEffect",
    "ConfettiEffect",
    "CountdownTimerEffect",
    "CursorTrailCometEffect",
    "CursorTrailEffect",
    "CursorTrailFireEffect",
    "CursorTrailGlowEffect",
    "CursorTrailLineEffect",
    "CursorTrailParticlesEffect",
    "CursorTrailRainbowEffect",
    "EmojiRainEffect",
    "FireworksEffect",
    "FrostedGlassEffect",
    "GlowEffect",
    "HighlightEffect",
    "MagneticHoverEffect",
    "MatrixRainEffect",
    "MorphingBackgroundEffect",
    "NeonGlowEffect",
    "PartyPopperEffect",
    "ProgressBarEffect",
    "RippleEffect",
    "ShockwaveEffect",
    "SnowEffect",
    "SparkleEffect",
    "SpotlightEffect",
    "StarBurstEffect",
    "SuccessCheckmarkEffect",
    "TextHighlightEffect",
    "TextScrambleEffect",
    "TooltipAnnotationEffect",
    "TypewriterEffect",
    "register_all_browser_effects",
]
