# Homebrew formula for demodsl — generated by .github/workflows/publish.yml.
#
# Install with:  brew install Fran-cois/demodsl/demodsl
#
# This formula ships the standalone PyInstaller binaries attached to each
# GitHub Release rather than building a Python virtualenv from source.
# A source build would need a `resource` stanza for every transitive
# dependency (playwright, pydantic, typer, ...), regenerated on every
# release. The release binaries are already built and smoke-tested by CI,
# so this stays correct on its own.
#
# The __PLACEHOLDER__ values are substituted by CI from the real assets.

class Demodsl < Formula
  desc "DSL-driven automated product demo video generator"
  homepage "https://fran-cois.github.io/demodsl"
  version "__VERSION__"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    on_arm do
      url "__URL_MACOS_ARM64__"
      sha256 "__SHA_MACOS_ARM64__"
    end
    on_intel do
      url "__URL_MACOS_X86_64__"
      sha256 "__SHA_MACOS_X86_64__"
    end
  end

  on_linux do
    on_intel do
      url "__URL_LINUX_X86_64__"
      sha256 "__SHA_LINUX_X86_64__"
    end
  end

  def install
    bin.install "demodsl"
  end

  def caveats
    <<~EOS
      Rendering a demo drives a real browser, and the standalone binary does
      not ship Playwright's Chromium. Commands that never touch a browser
      (validate, capabilities, estimate, qa, eval) work as-is.

      To record a page, install the browser once:
        pipx run playwright install chromium

      ffmpeg is pulled in as a dependency and is used for the final encode.
    EOS
  end

  test do
    assert_match "Usage", shell_output("#{bin}/demodsl --help")
    assert_match version.to_s, shell_output("#{bin}/demodsl capabilities")
  end
end
